'use client'

import { useState } from 'react'

import brandLogos from '@/lib/brand-logos.json'

/**
 * Theme-aware brand icon, self-hosted from public/logos/ (Simple Icons glyphs
 * generated by scripts/gen-brand-logos.mjs from lib/brand-logos.json). Brands
 * whose default glyph is near-black (invisible in dark) or near-white
 * (invisible in light) get a per-theme tint and render two <img> swapped via
 * the `dark:` variant. Everything else renders a single brand-coloured icon.
 * Slugs without a logo render a monogram.
 */
const LOGOS = new Set<string>(brandLogos.slugs)
const TINT: Record<string, { light?: string; dark?: string }> = brandLogos.tint

/** Same-origin URL of a slug's logo, optionally in a tint colour. */
export function brandLogoUrl(slug: string, color?: string): string {
  return `/logos/${slug}${color ? `-${color}` : ''}.svg`
}

export function BrandIcon({
  slug,
  label,
  size = 20,
  imgClass = '',
}: {
  slug: string | null
  label: string
  size?: number
  imgClass?: string
}) {
  const [failed, setFailed] = useState(false)
  const monogram = label.replace(/[^a-zA-Z0-9]/g, '').charAt(0).toUpperCase() || '•'

  if (failed || !slug || !LOGOS.has(slug)) {
    return (
      <span
        aria-hidden="true"
        className="inline-flex items-center justify-center font-mono font-bold text-ak-graphite"
        style={{ width: size, height: size, fontSize: size * 0.7 }}
      >
        {monogram}
      </span>
    )
  }

  const url = (c?: string) => brandLogoUrl(slug, c)
  const common = {
    alt: '',
    width: size,
    height: size,
    loading: 'lazy' as const,
    onError: () => setFailed(true),
    style: { width: size, height: size },
  }
  const tint = TINT[slug]

  if (!tint) {
    // eslint-disable-next-line @next/next/no-img-element
    return <img src={url()} {...common} className={`object-contain ${imgClass}`} />
  }

  return (
    <>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={url(tint.light)} {...common} className={`object-contain dark:hidden ${imgClass}`} />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={url(tint.dark)} {...common} className={`hidden object-contain dark:block ${imgClass}`} />
    </>
  )
}
