// Service barrel — re-exports + side-effect registration of each descriptor.
// `pnpm gen:integration <name>` appends a line here.
export { slackIntegration } from './slack'
export { discordIntegration } from './discord'
export { gmailIntegration } from './gmail'
export { twilioIntegration } from './twilio'
export * from './email'
export * from './teams'
export { githubIntegration } from './github'
export { githubActionsIntegration } from './github-actions'
export { sentryIntegration } from './sentry'
export { linearIntegration } from './linear'
export { linearTriageIntegration } from './linear-triage'
export { jiraIntegration } from './jira'
export { pagerdutyIntegration } from './pagerduty'
