'use client'

import { useState } from 'react'

import brandLogos from '@/lib/brand-logos.json'

// Theme-aware brand glyph, self-hosted from public/logos/ (Simple Icons, generated by
// scripts/gen-brand-logos.mjs from lib/brand-logos.json). Near-black brands get a light
// fill in dark; brands without a logo render a monogram.
const LOGOS = new Set<string>(brandLogos.slugs)
const TINT: Record<string, { light?: string; dark?: string }> = brandLogos.tint

export function brandLogoUrl(slug: string, color?: string): string {
  return `/logos/${slug}${color ? `-${color}` : ''}.svg`
}

export function BrandIcon({ slug, label, size = 18 }: { slug: string; label: string; size?: number }) {
  const [failed, setFailed] = useState(false)
  if (failed || !LOGOS.has(slug)) {
    const m = label.replace(/[^a-zA-Z0-9]/g, '').charAt(0).toUpperCase() || '•'
    return (
      <span
        aria-hidden="true"
        className="inline-flex items-center justify-center font-mono font-bold text-ak-graphite"
        style={{ width: size, height: size, fontSize: size * 0.7 }}
      >
        {m}
      </span>
    )
  }
  const url = (c?: string) => brandLogoUrl(slug, c)
  const t = TINT[slug]
  const common = {
    alt: '',
    width: size,
    height: size,
    loading: 'lazy' as const,
    onError: () => setFailed(true),
    style: { width: size, height: size },
  }
  if (!t) {
    // eslint-disable-next-line @next/next/no-img-element
    return <img src={url()} {...common} className="object-contain" />
  }
  return (
    <>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={url(t.light)} {...common} className="object-contain dark:hidden" />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={url(t.dark)} {...common} className="hidden object-contain dark:block" />
    </>
  )
}
