/**
 * Query-time retriever for the Ask-the-docs chat.
 *
 * Loads the committed index (lib/ask-index/index.json — generated by
 * scripts/gen-ask-index.mjs) and serves retrieval through `@agentskit/rag`'s
 * `createRAG`. The vector store is an in-process cosine index over the committed
 * embeddings: no vectra binary, no writable filesystem, so it runs cleanly in a
 * Node serverless route. Retrieval orchestration, chunking-on-query, and BM25
 * hybrid reranking are all reused from the package — only the tiny cosine store
 * and the index loader live here.
 *
 * The returned `Retriever` caps its output at ~3k tokens of cited context so
 * the prompt budget stays bounded regardless of how many chunks match.
 *
 * RFC-0006 D6: the 20 MB index.json is loaded lazily on first retrieval and
 * cached in-process, so it is NOT part of the module-load graph. Serverless
 * cold-start and bundle size are unaffected.
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'
import type {
  EmbedFn,
  RetrievedDocument,
  Retriever,
  VectorDocument,
  VectorMemory,
  VectorSearchOptions,
} from '@agentskit/core'
import { createRAG, createHybridRetriever } from '@agentskit/rag'
import { embed as defaultEmbed } from './embed'
import type { DocChunkMetadata } from './ingest'

interface IndexRecord {
  id: string
  content: string
  source?: string
  embedding: number[]
  metadata: DocChunkMetadata
}

interface IndexSnapshot {
  schemaVersion: number
  model: string
  dim: number
  count: number
  records: IndexRecord[]
}

/** Lazily-loaded snapshot — populated on first retrieve() call, then reused. */
let cachedSnapshot: IndexSnapshot | undefined

/**
 * Load the committed index from disk on first call; return the cached copy
 * thereafter. Using readFileSync with a path resolved from import.meta.url
 * ensures bundlers cannot inline the JSON at build time — it is read at Node
 * runtime, not at module-parse time.
 */
function loadSnapshot(): IndexSnapshot {
  if (cachedSnapshot) return cachedSnapshot
  const dir = dirname(fileURLToPath(import.meta.url))
  const indexPath = join(dir, '../ask-index/index.json')
  const raw = readFileSync(indexPath, 'utf8')
  cachedSnapshot = JSON.parse(raw) as IndexSnapshot
  return cachedSnapshot
}

/** ~4 chars per token; cap cited context near 3k tokens (~12k chars). */
const MAX_CONTEXT_CHARS = 12_000
/** Vector candidates pulled before hybrid rerank. */
const CANDIDATE_POOL = 16
/** Chunks returned to the prompt after reranking. */
const TOP_K = 6

function cosine(a: number[], b: number[]): number {
  // Vectors are L2-normalized at embed time, so dot product == cosine.
  let dot = 0
  const n = Math.min(a.length, b.length)
  for (let i = 0; i < n; i++) dot += a[i] * b[i]
  return dot
}

/**
 * Build an in-memory `VectorMemory` from the committed records. Implements only
 * the read path the RAG retrieve flow needs (`store` is a no-op seed; `search`
 * does cosine). Threshold/topK honored to match the contract.
 */
function createInMemoryVectorStore(records: IndexRecord[]): VectorMemory {
  const docs: VectorDocument[] = records.map((r) => ({
    id: r.id,
    content: r.content,
    embedding: r.embedding,
    metadata: { ...r.metadata, source: r.source },
  }))

  return {
    store(extra: VectorDocument[]) {
      for (const d of extra) docs.push(d)
    },
    search(embedding: number[], options?: VectorSearchOptions): RetrievedDocument[] {
      const topK = options?.topK ?? TOP_K
      const threshold = options?.threshold ?? 0
      return docs
        .map((d) => ({
          id: d.id,
          content: d.content,
          score: cosine(embedding, d.embedding),
          metadata: d.metadata,
        }))
        .filter((d) => d.score >= threshold)
        .sort((a, b) => b.score - a.score)
        .slice(0, topK)
    },
  }
}

export interface DocsRetrieverOptions {
  /** Override the embedder (tests). Defaults to the local ONNX embed. */
  embed?: EmbedFn
  /** Max characters of cited context to emit. Defaults to ~3k tokens. */
  maxContextChars?: number
  /** Disable BM25 hybrid rerank (pure vector). Default false. */
  vectorOnly?: boolean
}

/** Trim a ranked list so total content stays under `maxChars`. */
function boundByChars(docs: RetrievedDocument[], maxChars: number): RetrievedDocument[] {
  const out: RetrievedDocument[] = []
  let used = 0
  for (const d of docs) {
    const len = d.content.length
    if (out.length > 0 && used + len > maxChars) break
    out.push(d)
    used += len
  }
  return out
}

/**
 * Build the docs `Retriever` over the committed index. Returns a bounded,
 * reranked set of cited chunks. Plug straight into `createRuntime({ retriever })`
 * or any `useChat` retriever slot.
 *
 * The index is loaded lazily on the first `retrieve()` call (RFC-0006 D6): the
 * 20 MB JSON is not part of the module-load graph and does not inflate cold-start
 * or bundle size. All retrieval behaviour is unchanged.
 */
export function createDocsRetriever(options: DocsRetrieverOptions = {}): Retriever {
  const embed = options.embed ?? defaultEmbed
  const maxChars = options.maxContextChars ?? MAX_CONTEXT_CHARS

  // Defer index access into the async retrieve path so createDocsRetriever()
  // itself remains synchronous. RAG + hybrid retriever are built on first call
  // and reused via closured references.
  let base: Retriever | undefined

  function ensureRetriever(): Retriever {
    if (base) return base
    const data = loadSnapshot()
    const store = createInMemoryVectorStore(data.records)
    const rag = createRAG({
      embed,
      store,
      // Inputs are pre-chunked; keep the query-side splitter inert.
      chunkSize: 1_000_000,
      chunkOverlap: 0,
      topK: CANDIDATE_POOL,
    })
    base = options.vectorOnly
      ? rag
      : createHybridRetriever(rag, {
          candidatePool: CANDIDATE_POOL,
          topK: TOP_K,
          // Semantic-heavier: keyword-matchy recipe/example siblings were
          // out-ranking the canonical leaf page at #1. Leaning on the vector score
          // promotes the conceptual page — measured MRR 0.546 → 0.678 with
          // recall@6 unchanged at 98% (eval: lib/ask/eval/retrieval.ts).
          vectorWeight: 0.85,
          bm25Weight: 0.15,
        })
    return base
  }

  return {
    async retrieve(request) {
      const docs = await ensureRetriever().retrieve(request)
      return boundByChars(docs, maxChars)
    },
  }
}

/**
 * Render retrieved chunks into a context block plus a citation list. Citations
 * use `[path#anchor]` so the model can link back to the exact doc section.
 */
export function formatCitedContext(docs: RetrievedDocument[]): {
  context: string
  citations: string[]
} {
  const citations: string[] = []
  const blocks: string[] = []

  for (const doc of docs) {
    const meta = (doc.metadata ?? {}) as Partial<DocChunkMetadata>
    const anchor = meta.anchor ? `${meta.path}#${meta.anchor}` : meta.path ?? ''
    const cite = anchor ? `[${anchor}]` : `[${doc.id}]`
    if (anchor && !citations.includes(anchor)) citations.push(anchor)
    blocks.push(`${cite}\n${doc.content}`)
  }

  return { context: blocks.join('\n\n---\n\n'), citations }
}
