export const PUBLIC_RESOURCE_TYPES = [
  'official',
  'article',
  'directory',
  'registry',
  'recognition',
  'community',
] as const

export const PUBLIC_RESOURCE_STATUSES = ['live', 'published', 'verified'] as const

export type PublicResourceType = (typeof PUBLIC_RESOURCE_TYPES)[number]
export type PublicResourceStatus = (typeof PUBLIC_RESOURCE_STATUSES)[number]

export type PublicResource = Readonly<{
  id: string
  title: string
  summary: string
  product: string
  publisher: string
  type: PublicResourceType
  status: PublicResourceStatus
  url: string
  verifiedAt: string
  topics: readonly string[]
}>

function ecosystemUrl(productId: string, path = ''): string {
  const product = ecosystem.products.find((candidate) => candidate.id === productId)

  if (!product) {
    throw new Error(`Unknown ecosystem product: ${productId}`)
  }

  return new URL(path, product.surfaces.home).toString()
}

export const publicResources: readonly PublicResource[] = [
  {
    id: 'agentskit-docs',
    title: 'AgentsKit documentation',
    summary: 'Canonical guides and API reference for the composable JavaScript agent toolkit.',
    product: 'AgentsKit',
    publisher: 'AgentsKit',
    type: 'official',
    status: 'live',
    url: ecosystemUrl('agentskit', '/docs'),
    verifiedAt: '2026-08-10',
    topics: ['agents', 'JavaScript', 'documentation'],
  },
  {
    id: 'agentskit-registry',
    title: 'AgentsKit Registry',
    summary: 'Source-owned agents that developers can inspect, copy, adapt, and keep.',
    product: 'Registry',
    publisher: 'AgentsKit',
    type: 'official',
    status: 'live',
    url: ecosystemUrl('registry'),
    verifiedAt: '2026-08-10',
    topics: ['agents', 'source ownership', 'registry'],
  },
  {
    id: 'agentskit-chat',
    title: 'AgentsKit Chat',
    summary: 'Open-source chat framework for building provider-independent AI product experiences.',
    product: 'Chat',
    publisher: 'AgentsKit',
    type: 'official',
    status: 'live',
    url: ecosystemUrl('agentskit-chat'),
    verifiedAt: '2026-08-10',
    topics: ['chat UI', 'frameworks', 'provider independence'],
  },
  {
    id: 'doc-bridge',
    title: 'Doc Bridge',
    summary: 'Deterministic documentation handoffs that tell coding agents where they may edit and how to verify changes.',
    product: 'Doc Bridge',
    publisher: 'AgentsKit',
    type: 'official',
    status: 'live',
    url: ecosystemUrl('doc-bridge'),
    verifiedAt: '2026-08-10',
    topics: ['MCP', 'documentation', 'coding agents'],
  },
  {
    id: 'agentskit-playbook',
    title: 'AgentsKit Playbook',
    summary: 'Executable engineering standards for software built with coding agents.',
    product: 'Playbook',
    publisher: 'AgentsKit',
    type: 'official',
    status: 'live',
    url: ecosystemUrl('playbook'),
    verifiedAt: '2026-08-10',
    topics: ['engineering standards', 'CI', 'coding agents'],
  },
  {
    id: 'doc-bridge-official-mcp-registry',
    title: 'Doc Bridge in the official MCP Registry',
    summary: 'Published MCP server metadata and current Doc Bridge release in the official registry.',
    product: 'Doc Bridge',
    publisher: 'Model Context Protocol',
    type: 'registry',
    status: 'verified',
    url: 'https://registry.modelcontextprotocol.io/?q=io.github.AgentsKit-io%2Fdoc-bridge',
    verifiedAt: '2026-08-03',
    topics: ['MCP', 'registry', 'documentation'],
  },
  {
    id: 'registry-official-mcp-registry',
    title: 'AgentsKit Registry in the official MCP Registry',
    summary: 'MCP connector for discovering source-owned agents from the AgentsKit Registry.',
    product: 'Registry',
    publisher: 'Model Context Protocol',
    type: 'registry',
    status: 'verified',
    url: 'https://registry.modelcontextprotocol.io/?q=io.github.AgentsKit-io%2Fagentskit-registry',
    verifiedAt: '2026-08-01',
    topics: ['MCP', 'agents', 'registry'],
  },
  {
    id: 'registry-smithery',
    title: 'AgentsKit Registry on Smithery',
    summary: 'Installable Registry MCP server listed for discovery by MCP users.',
    product: 'Registry',
    publisher: 'Smithery',
    type: 'registry',
    status: 'published',
    url: 'https://smithery.ai/servers/agentskit/registry',
    verifiedAt: '2026-07-28',
    topics: ['MCP', 'agents', 'discovery'],
  },
  {
    id: 'registry-glama',
    title: 'AgentsKit Registry on Glama',
    summary: 'Public MCP connector profile for the source-owned agent registry.',
    product: 'Registry',
    publisher: 'Glama',
    type: 'registry',
    status: 'published',
    url: 'https://glama.ai/mcp/connectors/io.github.AgentsKit-io/agentskit-registry',
    verifiedAt: '2026-08-03',
    topics: ['MCP', 'agents', 'discovery'],
  },
  {
    id: 'doc-bridge-glama',
    title: 'Doc Bridge on Glama',
    summary: 'Verified MCP server profile for giving coding agents deterministic documentation handoffs.',
    product: 'Doc Bridge',
    publisher: 'Glama',
    type: 'registry',
    status: 'published',
    url: 'https://glama.ai/mcp/servers/AgentsKit-io/doc-bridge',
    verifiedAt: '2026-07-22',
    topics: ['MCP', 'documentation', 'coding agents'],
  },
  {
    id: 'doc-bridge-mcpservers',
    title: 'Doc Bridge on MCP Servers',
    summary: 'Approved MCP server listing for discovering and evaluating Doc Bridge.',
    product: 'Doc Bridge',
    publisher: 'MCP Servers',
    type: 'registry',
    status: 'published',
    url: 'https://mcpservers.org/servers/agentskit-io/doc-bridge',
    verifiedAt: '2026-08-06',
    topics: ['MCP', 'documentation', 'discovery'],
  },
  {
    id: 'agentskit-mcp-npm',
    title: '@agentskit/mcp on npm',
    summary: 'Published MCP package for exposing AgentsKit tools and resources through Model Context Protocol clients.',
    product: 'AgentsKit',
    publisher: 'npm',
    type: 'registry',
    status: 'published',
    url: 'https://www.npmjs.com/package/@agentskit/mcp',
    verifiedAt: '2026-07-30',
    topics: ['MCP', 'JavaScript', 'packages'],
  },
  {
    id: 'doc-bridge-npm',
    title: '@agentskit/doc-bridge on npm',
    summary: 'Published Doc Bridge package for deterministic human-to-agent documentation handoffs.',
    product: 'Doc Bridge',
    publisher: 'npm',
    type: 'registry',
    status: 'published',
    url: 'https://www.npmjs.com/package/@agentskit/doc-bridge',
    verifiedAt: '2026-08-09',
    topics: ['MCP', 'documentation', 'packages'],
  },
  {
    id: 'code-review-marketplace',
    title: 'AgentsKit Code Review on GitHub Marketplace',
    summary: 'A reusable GitHub Action for focused model-assisted review before merge.',
    product: 'Code Review',
    publisher: 'GitHub Marketplace',
    type: 'registry',
    status: 'live',
    url: 'https://github.com/marketplace/actions/agentskit-code-review',
    verifiedAt: '2026-08-10',
    topics: ['code review', 'GitHub Actions', 'CI'],
  },
  {
    id: 'doc-bridge-marketplace',
    title: 'Doc Bridge Gate on GitHub Marketplace',
    summary: 'CI gate that catches stale or incomplete human-to-agent documentation handoffs.',
    product: 'Doc Bridge',
    publisher: 'GitHub Marketplace',
    type: 'registry',
    status: 'live',
    url: 'https://github.com/marketplace/actions/doc-bridge-gate',
    verifiedAt: '2026-08-10',
    topics: ['documentation', 'GitHub Actions', 'CI'],
  },
  {
    id: 'article-agent-stack',
    title: 'Six open-source pieces, one JavaScript agent stack',
    summary: 'Why a complete agent stack should remain composable instead of forcing teams into a single provider or platform.',
    product: 'Ecosystem',
    publisher: 'DEV Community',
    type: 'article',
    status: 'published',
    url: 'https://dev.to/agentskit/six-open-source-pieces-one-javascript-agent-stack-2of4',
    verifiedAt: '2026-07-27',
    topics: ['architecture', 'open source', 'provider independence'],
  },
  {
    id: 'article-replaceable-stack',
    title: 'The model call was the easy part: keeping an agent stack replaceable',
    summary: 'A practical argument for contracts and replaceable providers across an agent system.',
    product: 'AgentsKit',
    publisher: 'Hashnode',
    type: 'article',
    status: 'published',
    url: 'https://agentskit.hashnode.dev/the-model-call-was-the-easy-part-keeping-an-agent-stack-replaceable',
    verifiedAt: '2026-08-01',
    topics: ['architecture', 'adapters', 'provider independence'],
  },
  {
    id: 'article-doc-bridge-edit-roots',
    title: 'I stopped asking coding agents to guess where they could edit',
    summary: 'How deterministic edit roots and verification commands reduce unsafe agent guesswork.',
    product: 'Doc Bridge',
    publisher: 'DEV Community',
    type: 'article',
    status: 'published',
    url: 'https://dev.to/agentskit/i-stopped-asking-coding-agents-to-guess-where-they-could-edit-206k',
    verifiedAt: '2026-07-28',
    topics: ['coding agents', 'documentation', 'safety'],
  },
  {
    id: 'article-playbook-enforcement',
    title: 'I stopped writing rules for coding agents that CI could not enforce',
    summary: 'Turning repository guidance into executable rules and repeatable CI evidence.',
    product: 'Playbook',
    publisher: 'DEV Community',
    type: 'article',
    status: 'published',
    url: 'https://dev.to/agentskit/i-stopped-writing-rules-for-coding-agents-that-ci-could-not-enforce-5hn9',
    verifiedAt: '2026-07-28',
    topics: ['coding agents', 'CI', 'engineering standards'],
  },
  {
    id: 'article-source-owned-agents',
    title: 'I stopped installing opaque AI agents and started copying their source',
    summary: 'Why inspectable, source-owned agents are easier to trust, adapt, and maintain.',
    product: 'Registry',
    publisher: 'DEV Community',
    type: 'article',
    status: 'published',
    url: 'https://dev.to/agentskit/i-stopped-installing-opaque-ai-agents-and-started-copying-their-source-6gb',
    verifiedAt: '2026-07-28',
    topics: ['agents', 'source ownership', 'open source'],
  },
  {
    id: 'article-safe-vector-memory',
    title: 'I removed an arbitrary SQL RPC from an agent memory adapter',
    summary: 'A concrete safety improvement for vector memory that replaced arbitrary SQL execution with constrained operations.',
    product: 'AgentsKit',
    publisher: 'Hashnode',
    type: 'article',
    status: 'published',
    url: 'https://agentskit.hashnode.dev/i-removed-an-arbitrary-sql-rpc-from-an-agent-memory-adapter',
    verifiedAt: '2026-08-05',
    topics: ['memory', 'Supabase', 'security'],
  },
  {
    id: 'article-stale-context',
    title: 'I made stale coding-agent context fail CI instead of failing silently',
    summary: 'A deterministic gate for detecting when agent instructions no longer match the repository.',
    product: 'Doc Bridge',
    publisher: 'DEV Community',
    type: 'article',
    status: 'published',
    url: 'https://dev.to/agentskit/i-made-stale-coding-agent-context-fail-ci-instead-of-failing-silently-3434',
    verifiedAt: '2026-08-06',
    topics: ['coding agents', 'documentation', 'CI'],
  },
  {
    id: 'article-framework-architecture',
    title: 'Your agent framework should not become your architecture',
    summary: 'Why stable contracts and replaceable integrations matter more than committing a product to one agent framework.',
    product: 'AgentsKit',
    publisher: 'HackerNoon',
    type: 'article',
    status: 'published',
    url: 'https://hackernoon.com/your-agent-framework-should-not-become-your-architecture',
    verifiedAt: '2026-08-06',
    topics: ['architecture', 'frameworks', 'provider independence'],
  },
  {
    id: 'article-replaceable-stack-medium',
    title: 'The model call was the easy part: keeping an agent stack replaceable',
    summary: 'A cross-published architecture essay about keeping models, memory, tools, and observability replaceable.',
    product: 'AgentsKit',
    publisher: 'Medium',
    type: 'article',
    status: 'published',
    url: 'https://medium.com/@emersonbraundev/the-model-call-was-the-easy-part-keeping-an-agent-stack-replaceable-6d354d27c920',
    verifiedAt: '2026-08-04',
    topics: ['architecture', 'adapters', 'provider independence'],
  },
  {
    id: 'agentskit-ai-directory',
    title: 'AgentsKit on AI Directory',
    summary: 'Reviewed public listing for the open-source JavaScript agent toolkit.',
    product: 'AgentsKit',
    publisher: 'AI Directory',
    type: 'directory',
    status: 'published',
    url: 'https://www.ai-directory.io/tool/agentskit',
    verifiedAt: '2026-08-10',
    topics: ['AI tools', 'open source', 'directory'],
  },
  {
    id: 'agentskit-peerlist',
    title: 'AgentsKit on Peerlist',
    summary: 'Public project and launch profile for the open-source AgentsKit ecosystem.',
    product: 'AgentsKit',
    publisher: 'Peerlist',
    type: 'directory',
    status: 'live',
    url: 'https://peerlist.io/emersonbraun/project/agentskit',
    verifiedAt: '2026-08-10',
    topics: ['developer tools', 'open source', 'launch'],
  },
  {
    id: 'agentskit-launch-llama',
    title: 'AgentsKit on Launch Llama',
    summary: 'Founder-oriented product profile describing the toolkit, its audience, and its core capabilities.',
    product: 'AgentsKit',
    publisher: 'Launch Llama',
    type: 'directory',
    status: 'published',
    url: 'https://tools.launchllama.co/products/agentskit',
    verifiedAt: '2026-08-10',
    topics: ['developer tools', 'AI agents', 'directory'],
  },
  {
    id: 'agentskit-reporanker',
    title: 'AgentsKit on RepoRanker',
    summary: 'Repository profile where developers can discover, evaluate, and review AgentsKit.',
    product: 'AgentsKit',
    publisher: 'RepoRanker',
    type: 'community',
    status: 'published',
    url: 'https://reporanker.com/repos/AgentsKit-io/agentskit',
    verifiedAt: '2026-08-06',
    topics: ['open source', 'reviews', 'contributors'],
  },
  {
    id: 'agentskit-saashub',
    title: 'AgentsKit on SaaSHub',
    summary: 'Verified software profile for discovering AgentsKit and comparing related developer tools.',
    product: 'AgentsKit',
    publisher: 'SaaSHub',
    type: 'directory',
    status: 'verified',
    url: 'https://www.saashub.com/agentskit',
    verifiedAt: '2026-08-06',
    topics: ['developer tools', 'software discovery', 'directory'],
  },
  {
    id: 'chat-saashub',
    title: 'AgentsKit Chat on SaaSHub',
    summary: 'Verified software profile for the open-source, provider-independent chat framework.',
    product: 'Chat',
    publisher: 'SaaSHub',
    type: 'directory',
    status: 'verified',
    url: 'https://www.saashub.com/agentskit-chat',
    verifiedAt: '2026-08-06',
    topics: ['chat UI', 'open source', 'software discovery'],
  },
  {
    id: 'agentskit-spot-startups',
    title: 'AgentsKit on Spot Startups',
    summary: 'Public startup profile for discovering the AgentsKit ecosystem and its open-source foundation.',
    product: 'AgentsKit',
    publisher: 'Spot Startups',
    type: 'directory',
    status: 'live',
    url: 'https://spotstartups.com/details.php?slug=agentskit',
    verifiedAt: '2026-08-05',
    topics: ['startup', 'open source', 'directory'],
  },
  {
    id: 'agentskit-llmshub',
    title: 'AgentsKit in the llmshub directory',
    summary: 'AI-readiness directory entry describing the provider-independent open-source JavaScript toolkit.',
    product: 'AgentsKit',
    publisher: 'llmshub.de',
    type: 'directory',
    status: 'published',
    url: 'https://llmshub.de/en/directory/',
    verifiedAt: '2026-08-07',
    topics: ['LLM visibility', 'open source', 'directory'],
  },
  {
    id: 'agentskit-stackshare',
    title: 'AgentsKit on StackShare',
    summary: 'Technology profile connecting AgentsKit to the tools and categories around agent development.',
    product: 'AgentsKit',
    publisher: 'StackShare',
    type: 'directory',
    status: 'published',
    url: 'https://stackshare.io/agentskit',
    verifiedAt: '2026-08-02',
    topics: ['developer tools', 'technology stack', 'directory'],
  },
  {
    id: 'agentskit-openhub',
    title: 'AgentsKit on Open Hub',
    summary: 'Open-source project profile with repository-derived activity and code analysis.',
    product: 'AgentsKit',
    publisher: 'Open Hub',
    type: 'directory',
    status: 'published',
    url: 'https://openhub.net/p/agentskit',
    verifiedAt: '2026-07-31',
    topics: ['open source', 'project activity', 'directory'],
  },
  {
    id: 'doc-bridge-openhub',
    title: 'Doc Bridge on Open Hub',
    summary: 'Repository-derived open-source activity and code analysis for Doc Bridge.',
    product: 'Doc Bridge',
    publisher: 'Open Hub',
    type: 'directory',
    status: 'verified',
    url: 'https://openhub.net/p/767976',
    verifiedAt: '2026-08-06',
    topics: ['open source', 'project activity', 'documentation'],
  },
  {
    id: 'chat-openhub',
    title: 'AgentsKit Chat on Open Hub',
    summary: 'Repository-derived open-source activity and code analysis for AgentsKit Chat.',
    product: 'Chat',
    publisher: 'Open Hub',
    type: 'directory',
    status: 'verified',
    url: 'https://openhub.net/p/767977',
    verifiedAt: '2026-08-06',
    topics: ['open source', 'project activity', 'chat UI'],
  },
  {
    id: 'registry-openhub',
    title: 'AgentsKit Registry on Open Hub',
    summary: 'Repository-derived open-source activity and code analysis for AgentsKit Registry.',
    product: 'Registry',
    publisher: 'Open Hub',
    type: 'directory',
    status: 'verified',
    url: 'https://openhub.net/p/767978',
    verifiedAt: '2026-08-06',
    topics: ['open source', 'project activity', 'agents'],
  },
  {
    id: 'playbook-openhub',
    title: 'AgentsKit Playbook on Open Hub',
    summary: 'Repository-derived open-source activity and code analysis for AgentsKit Playbook.',
    product: 'Playbook',
    publisher: 'Open Hub',
    type: 'directory',
    status: 'verified',
    url: 'https://openhub.net/p/767979',
    verifiedAt: '2026-08-06',
    topics: ['open source', 'project activity', 'engineering standards'],
  },
  {
    id: 'code-review-openhub',
    title: 'AgentsKit Code Review on Open Hub',
    summary: 'Repository-derived open-source activity and code analysis for AgentsKit Code Review.',
    product: 'Code Review',
    publisher: 'Open Hub',
    type: 'directory',
    status: 'verified',
    url: 'https://openhub.net/p/767980',
    verifiedAt: '2026-08-06',
    topics: ['open source', 'project activity', 'code review'],
  },
  {
    id: 'agentskit-product-hunt',
    title: 'AgentsKit on Product Hunt',
    summary: 'Product profile for following the toolkit and its public launch activity.',
    product: 'AgentsKit',
    publisher: 'Product Hunt',
    type: 'directory',
    status: 'live',
    url: 'https://www.producthunt.com/products/agentskit',
    verifiedAt: '2026-08-10',
    topics: ['product', 'launch', 'community'],
  },
  {
    id: 'agentskit-libhunt',
    title: 'AgentsKit on LibHunt',
    summary: 'Open-source JavaScript project listing and alternatives profile.',
    product: 'AgentsKit',
    publisher: 'LibHunt',
    type: 'directory',
    status: 'published',
    url: 'https://www.libhunt.com/r/agentskit',
    verifiedAt: '2026-08-01',
    topics: ['JavaScript', 'open source', 'directory'],
  },
  {
    id: 'agentskit-codetriage',
    title: 'AgentsKit on CodeTriage',
    summary: 'Contributor discovery page that connects volunteers with open AgentsKit issues.',
    product: 'AgentsKit',
    publisher: 'CodeTriage',
    type: 'community',
    status: 'published',
    url: 'https://www.codetriage.com/agentskit-io/agentskit',
    verifiedAt: '2026-08-06',
    topics: ['contributors', 'open source', 'issues'],
  },
  {
    id: 'agentskit-openssf',
    title: 'AgentsKit OpenSSF Best Practices',
    summary: 'Public evidence for the project’s OpenSSF baseline security and open-source practices.',
    product: 'AgentsKit',
    publisher: 'OpenSSF',
    type: 'recognition',
    status: 'verified',
    url: 'https://www.bestpractices.dev/en/projects/13861',
    verifiedAt: '2026-08-10',
    topics: ['security', 'open source', 'best practices'],
  },
  {
    id: 'chat-openssf',
    title: 'AgentsKit Chat OpenSSF Best Practices',
    summary: 'Public baseline evidence for the open-source chat framework.',
    product: 'Chat',
    publisher: 'OpenSSF',
    type: 'recognition',
    status: 'verified',
    url: 'https://www.bestpractices.dev/en/projects/13866',
    verifiedAt: '2026-08-10',
    topics: ['security', 'open source', 'best practices'],
  },
  {
    id: 'registry-openssf',
    title: 'AgentsKit Registry OpenSSF Best Practices',
    summary: 'Public baseline evidence for the source-owned agent registry.',
    product: 'Registry',
    publisher: 'OpenSSF',
    type: 'recognition',
    status: 'verified',
    url: 'https://www.bestpractices.dev/en/projects/13872',
    verifiedAt: '2026-08-10',
    topics: ['security', 'open source', 'best practices'],
  },
  {
    id: 'playbook-openssf',
    title: 'AgentsKit Playbook OpenSSF Best Practices',
    summary: 'Public baseline evidence for the executable engineering playbook.',
    product: 'Playbook',
    publisher: 'OpenSSF',
    type: 'recognition',
    status: 'verified',
    url: 'https://www.bestpractices.dev/en/projects/13878',
    verifiedAt: '2026-08-10',
    topics: ['security', 'open source', 'best practices'],
  },
] as const satisfies readonly PublicResource[]

export function resourcesByType(type: PublicResourceType): readonly PublicResource[] {
  return publicResources.filter((resource) => resource.type === type)
}
import ecosystem from './ecosystem.json'
