#!/usr/bin/env node
/**
 * sync-brand — generate per-property brand CSS from the canonical brand/tokens.json.
 *
 * The ecosystem decision is "copy tokens per repo" — but the copies are GENERATED,
 * never hand-edited, so they can't drift. This script writes a CSS custom-property
 * block for a target property; each repo runs it in prebuild and a check-brand-drift
 * gate fails if the committed copy differs from a fresh generate.
 *
 *   node scripts/sync-brand.mjs --property agentskit --out apps/docs-next/app/brand-tokens.css
 *   node scripts/sync-brand.mjs --property playbook  --out path/in/sibling/repo.css
 *
 * Property ∈ agentskit | akos | playbook | registry. Structure/type/radii/motion
 * are identical across all; only the accent differs (one family, per-property accent).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tokens = JSON.parse(readFileSync(join(root, 'brand', 'tokens.json'), 'utf8'))

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`)
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback
}

const property = arg('property', 'agentskit')
const out = arg('out', null)
const format = arg('format', 'ak') // 'ak' = full --ak-* file; 'landing' = in-place @theme markers
const check = process.argv.includes('--check')

if (!tokens.accent[property]) {
  console.error(`Unknown property "${property}". Known: ${Object.keys(tokens.accent).join(', ')}`)
  process.exit(1)
}

// landing format: regenerate the --color-* block between ecobrand markers in an
// existing Tailwind v4 @theme (dark-only). Single-sourced from tokens.json.
if (format === 'landing') {
  if (!out) { console.error('--format landing requires --out'); process.exit(1) }
  const d = tokens.color.dark
  const a = tokens.accent[property]
  const block = [
    `  --color-bg: ${d.bg};`,
    `  --color-bg-soft: ${d.surface};`,
    `  --color-fg: ${d.fg};`,
    `  --color-fg-soft: ${d.muted};`,
    `  --color-border: ${d.border};`,
    `  --color-accent: ${a.dark};`,
    `  --color-accent-soft: ${a.softDark};`,
    `  --color-success: ${a.dark};`,
  ].join('\n')
  const target = resolve(root, out)
  const src = readFileSync(target, 'utf8')
  const re = /(\/\* ecobrand:landing-start[^\n]*\n)[\s\S]*?(\n\s*\/\* ecobrand:landing-end \*\/)/
  if (!re.test(src)) { console.error(`brand: ${out} missing ecobrand:landing markers.`); process.exit(1) }
  const next = src.replace(re, `$1${block}$2`)
  if (check) {
    if (src !== next) { console.error(`brand drift: ${out} out of sync with tokens. Run sync-brand --format landing.`); process.exit(1) }
    console.log(`brand ok: ${out} matches tokens (landing/${property}).`)
  } else {
    writeFileSync(target, next)
    console.log(`brand written: ${out} (landing/${property}).`)
  }
  process.exit(0)
}

function block(scheme) {
  const c = tokens.color[scheme]
  const a = tokens.accent[property][scheme]
  const lines = [
    `  --ak-bg: ${c.bg};`,
    `  --ak-surface: ${c.surface};`,
    `  --ak-border: ${c.border};`,
    `  --ak-fg: ${c.fg};`,
    `  --ak-muted: ${c.muted};`,
    `  --ak-blue: ${c.blue};`,
    `  --ak-red: ${c.red};`,
    `  --ak-green: ${c.green};`,
    `  --ak-accent: ${a};`,
  ]
  return lines.join('\n')
}

const radii = Object.entries(tokens.radius).map(([k, v]) => `  --ak-radius-${k}: ${v};`).join('\n')
const motion = [
  `  --ak-ease: ${tokens.motion.ease};`,
  `  --ak-dur-fast: ${tokens.motion.fast};`,
  `  --ak-dur-base: ${tokens.motion.base};`,
  `  --ak-dur-slow: ${tokens.motion.slow};`,
].join('\n')

const css = `/* GENERATED by scripts/sync-brand.mjs from brand/tokens.json — DO NOT EDIT.
 * Property: ${property}. Run \`node scripts/sync-brand.mjs --property ${property}\` to regenerate. */
:root {
  --ak-font-body: ${tokens.font.body};
  --ak-font-mono: ${tokens.font.mono};
  --ak-font-display: ${tokens.font.display};
${radii}
${motion}
${block('light')}
}
.dark, [data-theme="dark"] {
${block('dark')}
}
`

if (check) {
  if (!out) { console.error('--check requires --out'); process.exit(1) }
  const existing = (() => { try { return readFileSync(resolve(root, out), 'utf8') } catch { return '' } })()
  if (existing.trim() !== css.trim()) {
    console.error(`brand drift: ${out} is out of sync with brand/tokens.json. Run sync-brand.`)
    process.exit(1)
  }
  console.log(`brand ok: ${out} matches tokens (${property}).`)
} else if (out) {
  const target = resolve(root, out)
  mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, css)
  console.log(`brand written: ${out} (${property}).`)
} else {
  process.stdout.write(css)
}
