import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { spawnSync } from 'node:child_process'

const isObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value)
const nonEmpty = (value) => typeof value === 'string' && value.trim().length > 0

export function loadJson(root, relativePath) {
  return JSON.parse(readFileSync(join(root, relativePath), 'utf8'))
}

export function mineRecipes(root, recipesDir = 'docs/ecosystem/content-pipeline/recipes') {
  const absolute = join(root, recipesDir)
  if (!existsSync(absolute)) return []
  return readdirSync(absolute)
    .filter((name) => name.endsWith('.json'))
    .map((name) => loadJson(root, join(recipesDir, name)))
    .filter((recipe) => nonEmpty(recipe.id) && nonEmpty(recipe.title))
}

export function verifyClaims(root, recipe, claimsPath = 'ecosystem-claims.json') {
  const claimsDoc = loadJson(root, claimsPath)
  const map = new Map()
  for (const product of claimsDoc.products ?? []) {
    for (const claim of product.claims ?? []) {
      map.set(`${product.productId}:${claim.id}`, claim)
    }
  }
  const verified = []
  const failures = []
  for (const ref of recipe.claims ?? []) {
    const key = `${ref.productId}:${ref.claimId}`
    const claim = map.get(key)
    if (!claim) {
      failures.push(`missing claim ${key}`)
      continue
    }
    if (typeof claim.value !== 'number' && typeof claim.value !== 'string') {
      failures.push(`claim ${key} has unusable value`)
      continue
    }
    verified.push({
      productId: ref.productId,
      claimId: ref.claimId,
      value: claim.value,
      noun: claim.noun ?? ref.claimId,
      evidence: claim.evidence ?? null,
    })
  }
  if (failures.length > 0) {
    return { ok: false, failures, verified }
  }
  if ((recipe.claims ?? []).length === 0) {
    return { ok: false, failures: ['recipe declares no claims to verify'], verified }
  }
  return { ok: true, failures: [], verified }
}

export function verifyExecutable(root, recipe) {
  const executable = recipe.executable
  if (!executable?.fixture || !Array.isArray(executable.command)) {
    return { ok: false, message: 'recipe missing executable fixture/command' }
  }
  if (!existsSync(join(root, executable.fixture))) {
    return { ok: false, message: `fixture missing: ${executable.fixture}` }
  }
  const [bin, ...args] = executable.command
  const run = spawnSync(bin, args, { cwd: root, encoding: 'utf8', env: process.env })
  if (run.status !== 0) {
    return { ok: false, message: `executable failed (${run.status}): ${run.stderr || run.stdout}` }
  }
  if (
    executable.expectStdoutIncludes &&
    !run.stdout.includes(executable.expectStdoutIncludes)
  ) {
    return { ok: false, message: 'executable stdout missing expected text' }
  }
  return { ok: true, message: 'executable verified', stdout: run.stdout.trim() }
}

function claimLine(verified) {
  return verified
    .map((claim) => `${claim.value} ${claim.noun}`)
    .join(', ')
}

export function repurpose(recipe, verifiedClaims, links) {
  const claimText = claimLine(verifiedClaims)
  const commands = recipe.commands.join('\n')
  const docsPage = [
    `---`,
    `title: ${recipe.title}`,
    `description: ${recipe.problem}`,
    `---`,
    ``,
    `# ${recipe.title}`,
    ``,
    recipe.problem,
    ``,
    `## Audience`,
    ``,
    recipe.audience,
    ``,
    `## Commands`,
    ``,
    '```bash',
    commands,
    '```',
    ``,
    `## Verified claims`,
    ``,
    claimText
      ? verifiedClaims
          .map(
            (claim) =>
              `- **${claim.productId}/${claim.claimId}**: ${claim.value} ${claim.noun} (from ecosystem-claims.json)`,
          )
          .join('\n')
      : '- (none)',
    ``,
    `## Citations`,
    ``,
    ...(recipe.citations ?? []).map((citation) => `- [${citation.title}](${citation.href})`),
    ``,
    `## Ecosystem next steps`,
    ``,
    ...links.map((link) => `- [${link.name}](${link.href}) — ${link.promise}`),
    ``,
    `> Draft generated by the content pipeline. Human approval required before publishing.`,
    ``,
  ].join('\n')

  const shortPost = [
    `${recipe.title}.`,
    ``,
    `Three commands. No provider key.`,
    ``,
    '```bash',
    recipe.commands[recipe.commands.length - 1],
    '```',
    ``,
    claimText ? `Built on AgentsKit (${claimText}).` : 'Built on AgentsKit.',
    ``,
    `Docs + fixture linked in the atom. Human-reviewed drafts only.`,
  ].join('\n')

  const thread = [
    `1/ ${recipe.title}`,
    ``,
    `Why it exists: ${recipe.problem}`,
    ``,
    `2/ The path:`,
    ...recipe.commands.map((command, index) => `${index + 1}. \`${command}\``),
    ``,
    `3/ Claims (generated, not hand-typed):`,
    ...verifiedClaims.map((claim) => `- ${claim.value} ${claim.noun}`),
    ``,
    `4/ Next products:`,
    ...links.slice(0, 3).map((link) => `- ${link.name}: ${link.promise}`),
    ``,
    `5/ This thread is a draft atom. Publishing requires explicit human approval.`,
  ].join('\n')

  const communityPost = [
    `## ${recipe.title}`,
    ``,
    recipe.problem,
    ``,
    `### Try it`,
    ``,
    '```bash',
    commands,
    '```',
    ``,
    `### Claims`,
    claimText,
    ``,
    `Source fixture: \`${recipe.executable.fixture}\``,
    ``,
    `Status: draft — awaiting human approval before community publish.`,
  ].join('\n')

  return {
    docsPage,
    shortPost,
    thread,
    communityPost,
    example: {
      kind: 'fixture-link',
      path: recipe.executable.fixture,
      commands: recipe.commands,
    },
  }
}

export function storyboard(recipe) {
  return [
    `# Storyboard — ${recipe.title}`,
    ``,
    `Format: 5-frame carousel / 15s silent GIF`,
    ``,
    `1. **Hook** — "${recipe.problem}"`,
    `2. **Install** — show \`${recipe.commands[0]}\``,
    `3. **Copy fixture** — show the agent.ts path`,
    `4. **Run** — terminal output includes the expected ready line`,
    `5. **Next step** — point to Registry / Playbook / Chat without inventing counts`,
    ``,
    `Accessibility: every frame needs alt text; prefer reduced-motion static frames.`,
    `No auto-publish — storyboard is a draft for human design review.`,
    ``,
  ].join('\n')
}

export function linkEcosystem(root, manifestPath = 'ecosystem.json') {
  const manifest = loadJson(root, manifestPath)
  return (manifest.products ?? [])
    .filter((product) => product.surfaces?.home || product.surfaces?.docs)
    .map((product) => ({
      id: product.id,
      name: product.name ?? product.id,
      promise: product.promise ?? '',
      href: product.surfaces?.docs ?? product.surfaces?.home,
    }))
}

export function review(atom) {
  return {
    status: 'needs-human-review',
    checklist: [
      {
        id: 'claims',
        ok: Array.isArray(atom.verifiedClaims) && atom.verifiedClaims.length > 0,
        note: 'Claims verified against ecosystem-claims.json',
      },
      {
        id: 'executable',
        ok: atom.executable?.ok === true,
        note: 'Source recipe executable passed',
      },
      {
        id: 'citations',
        ok: (atom.recipe?.citations ?? []).length > 0,
        note: 'Citations present',
      },
      {
        id: 'no-autonomous-publish',
        ok: atom.publish?.status !== 'published',
        note: 'Publisher must not mark published without human approval',
      },
      {
        id: 'doc-bridge',
        ok: true,
        note: 'Docs changes must pass pnpm docs:bridge:gate before merge',
      },
      {
        id: 'code-review',
        ok: true,
        note: 'Implementation diffs should run through Code Review CLI',
      },
      {
        id: 'playbook',
        ok: true,
        note: 'Agent-produced content should meet Playbook production standards',
      },
    ],
    requiresHumanApproval: true,
  }
}

export function preparePublish(atom, approval) {
  if (!isObject(approval) || approval.approved !== true) {
    return {
      status: 'blocked',
      reason: 'Human approval required before publish packaging',
      channels: [],
    }
  }
  if (!nonEmpty(approval.approvedBy) || !nonEmpty(approval.approvedOn)) {
    throw new Error('approval requires approvedBy and approvedOn')
  }
  if (approval.approved !== true) {
    throw new Error('approval.approved must be true')
  }
  // Never call social APIs. Only package draft paths for a human to post.
  return {
    status: 'ready-for-human-publish',
    approvedBy: approval.approvedBy,
    approvedOn: approval.approvedOn,
    channels: [
      { id: 'docs', artifact: 'docs.mdx', action: 'open-pr' },
      { id: 'x-short', artifact: 'social-short.md', action: 'manual-post' },
      { id: 'x-thread', artifact: 'social-thread.md', action: 'manual-post' },
      { id: 'carousel', artifact: 'carousel-storyboard.md', action: 'manual-design' },
      { id: 'community', artifact: 'community-post.md', action: 'open-pr' },
    ],
  }
}

export function runPipeline(root, recipeId, { runExecutable = true } = {}) {
  const recipes = mineRecipes(root)
  const recipe = recipes.find((entry) => entry.id === recipeId)
  if (!recipe) throw new Error(`recipe not found: ${recipeId}`)

  const claims = verifyClaims(root, recipe)
  if (!claims.ok) {
    throw new Error(`claim verification failed: ${claims.failures.join('; ')}`)
  }

  let executable = { ok: !runExecutable, message: 'skipped' }
  if (runExecutable) {
    executable = verifyExecutable(root, recipe)
    if (!executable.ok) throw new Error(executable.message)
  }

  const links = linkEcosystem(root)
  const variants = repurpose(recipe, claims.verified, links)
  const board = storyboard(recipe)
  const atom = {
    id: recipe.id,
    generatedAt: new Date().toISOString(),
    recipe,
    verifiedClaims: claims.verified,
    executable,
    links,
    variants,
    storyboard: board,
  }
  atom.review = review(atom)

  const approvalPath = join(
    root,
    'docs/ecosystem/content-pipeline/atoms',
    recipe.id,
    'APPROVAL.json',
  )
  let approval = { approved: false }
  if (existsSync(approvalPath)) {
    approval = JSON.parse(readFileSync(approvalPath, 'utf8'))
  }
  atom.publish = preparePublish(atom, approval)

  return atom
}

export function writeAtom(root, atom) {
  const dir = join(root, 'docs/ecosystem/content-pipeline/atoms', atom.id)
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, 'atom.json'), `${JSON.stringify(atom, null, 2)}\n`)
  writeFileSync(join(dir, 'docs.mdx'), atom.variants.docsPage)
  writeFileSync(join(dir, 'social-short.md'), `${atom.variants.shortPost}\n`)
  writeFileSync(join(dir, 'social-thread.md'), `${atom.variants.thread}\n`)
  writeFileSync(join(dir, 'community-post.md'), `${atom.variants.communityPost}\n`)
  writeFileSync(join(dir, 'carousel-storyboard.md'), atom.storyboard)
  writeFileSync(
    join(dir, 'review.md'),
    [
      `# Review — ${atom.id}`,
      ``,
      `Status: **${atom.review.status}**`,
      ``,
      ...atom.review.checklist.map(
        (item) => `- [${item.ok ? 'x' : ' '}] ${item.id}: ${item.note}`,
      ),
      ``,
      `Publish package: **${atom.publish.status}**`,
      atom.publish.reason ? `Reason: ${atom.publish.reason}` : '',
      ``,
    ]
      .filter(Boolean)
      .join('\n'),
  )
  const approvalPath = join(dir, 'APPROVAL.json')
  if (!existsSync(approvalPath)) {
    writeFileSync(
      approvalPath,
      `${JSON.stringify(
        {
          approved: false,
          approvedBy: null,
          approvedOn: null,
          notes: 'Set approved=true with approvedBy/approvedOn after HITL review. Publisher never auto-posts.',
        },
        null,
        2,
      )}\n`,
    )
  }
  writeFileSync(
    join(dir, 'example.json'),
    `${JSON.stringify(atom.variants.example, null, 2)}\n`,
  )
  return dir
}

/**
 * Optional LLM-backed role factory placeholders that mirror Registry agent contracts.
 * Offline CI uses the deterministic roles above; adapters can be injected later.
 */
export function createClaimVerifierRole(config = {}) {
  return {
    name: 'claim-verifier',
    registryAgentId: 'content-fact-checker',
    async run(recipe, ctx) {
      return verifyClaims(ctx.root, recipe)
    },
    // When an adapter is supplied by a host, callers may swap in Registry agent:
    // createContentFactCheckerAgent({ adapter: config.adapter })
    adapter: config.adapter ?? null,
  }
}

export function createRepurposerRole(config = {}) {
  return {
    name: 'content-repurposer',
    registryAgentId: 'content-repurpose-matrix',
    async run(recipe, verifiedClaims, links) {
      return repurpose(recipe, verifiedClaims, links)
    },
    adapter: config.adapter ?? null,
  }
}
